Author's name removed
utopia-php/logger pull request #15
Opened 2022-10-10 12:48 UTC by samarth2812

2022-10-12 08:50 UTC, Meldiron commented
Linking issue: https://github.com/appwrite/appwrite/issues/4407

2022-10-12 08:50 UTC, Meldiron requested changes
One tiny comment 🤏 I can mark as approved once resolved.

2022-10-12 08:50 UTC, Meldiron commented on tests/LoggerTest.php
> - * @author Eldad Fux <eldad@appwrite.io>
Let's remove the whole comment blocks, please.

2022-10-31 16:32 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-07 18:00 UTC, stnguyen90 commented
Closing as a stale duplicate

2022-11-07 18:00 UTC, closed without merging