Added RollBar Logger Changes
utopia-php/logger pull request #25
Opened 2023-04-01 09:36 UTC by pranjalg13

Closes #4208

2023-04-01 09:36 UTC, pranjalg13 commented
@christyjacob4 Please review this once

2023-04-01 09:39 UTC, pranjalg13 commented
![Uploading Screenshot 2023-04-01 at 3.09.06 PM.png…]()

2023-04-03 17:18 UTC, pranjalg13 commented
<img width="1278" alt="Screenshot 2023-04-01 at 3 09 06 PM" src="https://user-images.githubusercontent.com/47600057/229581495-37bc845f-7f26-4c8e-805c-5ce4096f47fc.png">
Screenshot for rollbar logs

2023-07-24 23:40 UTC, stnguyen90 commented
Successful test: 

<img width="1328" alt="image" src="https://github.com/utopia-php/logger/assets/1477010/2795cdf6-18fb-4bc2-8c20-45d6789b2591">

2023-07-24 23:50 UTC, stnguyen90 commented
example with proper stack trace:

<img width="1322" alt="image" src="https://github.com/utopia-php/logger/assets/1477010/8445781e-d364-405b-a01b-ba12491fa059">

2023-07-24 23:53 UTC, stnguyen90 requested changes
Great PR! Before we merge this, would you please remove the .DS_Store file from the PR?

2023-07-26 21:34 UTC, stnguyen90 requested changes
It looks like there's a lint error. Would you please run the formatter?

2023-07-27 21:55 UTC, stnguyen90 approved these changes
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

@christyjacob4, I think this is good to merge, but we need to add the `TEST_ROLLBAR_KEY` secret for the tests, right?

2025-12-15 08:54 UTC, closed without merging