Added LogOwl Adapter
utopia-php/logger pull request #8
Opened 2022-01-19 19:46 UTC by vermakhushboo

2022-01-20 05:21 UTC, abnegate reviewed
We could update the readme to show an example with LogOwl as well as add it to the supported adapter list 🙂 otherwise looks good to me 👍

2022-01-24 09:01 UTC, Meldiron requested changes
Great PR 🥳 Left my comments

2022-01-31 16:34 UTC, vermakhushboo commented on tests/LoggerTest.php
> +         $adapter = new LogOwl(\getenv("TEST_LOGOWL_KEY"));
The test API key has been generated, need to set it.

2022-02-01 13:16 UTC, Meldiron commented on tests/LoggerTest.php
> +         $adapter = new LogOwl(\getenv("TEST_LOGOWL_KEY"));
API key set. Resolving the conversation

2022-02-01 13:20 UTC, Meldiron commented
> We could update the readme to show an example with LogOwl as well as add it to the supported adapter list 🙂 otherwise looks good to me 👍

Took care of that. Also fixed existing README examples a little.

2022-02-01 17:07 UTC, closed without merging